package org.domain.SeamAmiciDelGas.entity;

// Generated 7-feb-2009 12.59.42 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "database_gas")
public class Account implements java.io.Serializable {

	private String username;
	private Utente utente;
	private Pagamentoelettronico pagamentoelettronico;
	private String pass;
	private boolean bloccato;
	private boolean elimato;
	private boolean cancellato;
	private boolean attivato;
	private Date dataRichiesta;
	private Date dataAccettazione;
	private int punteggioFeedback;
	private Set<Itinerario> itinerarios = new HashSet<Itinerario>(0);
	private Set<Questionario> questionarios = new HashSet<Questionario>(0);
	private Set<Feedback> feedbacksForSegnalatore = new HashSet<Feedback>(0);
	private Set<Cybercontadino> cybercontadinos = new HashSet<Cybercontadino>(0);
	private Set<Feedback> feedbacksForValidatore = new HashSet<Feedback>(0);
	private Set<Feedback> feedbacksForSegnalatore_1 = new HashSet<Feedback>(0);
	private Set<Ordine> ordines = new HashSet<Ordine>(0);
	private Set<Itinerario> itinerarios_1 = new HashSet<Itinerario>(0);
	private Set<Ruolo> ruolos = new HashSet<Ruolo>(0);
	private Set<Cybercontadino> cybercontadinos_1 = new HashSet<Cybercontadino>(
			0);
	private Set<Ruolo> ruolos_1 = new HashSet<Ruolo>(0);
	private Set<Feedback> feedbacksForDestinatario = new HashSet<Feedback>(0);
	private Set<Feedback> feedbacksForDestinatario_1 = new HashSet<Feedback>(0);
	private Set<Feedback> feedbacksForValidatore_1 = new HashSet<Feedback>(0);
	private Set<Ordine> ordines_1 = new HashSet<Ordine>(0);
	private Set<Questionario> questionarios_1 = new HashSet<Questionario>(0);

	public Account() {
	}

	public Account(String username, Utente utente, String pass,
			boolean bloccato, boolean elimato, boolean cancellato,
			boolean attivato, Date dataRichiesta, int punteggioFeedback) {
		this.username = username;
		this.utente = utente;
		this.pass = pass;
		this.bloccato = bloccato;
		this.elimato = elimato;
		this.cancellato = cancellato;
		this.attivato = attivato;
		this.dataRichiesta = dataRichiesta;
		this.punteggioFeedback = punteggioFeedback;
	}

	public Account(String username, Utente utente,
			Pagamentoelettronico pagamentoelettronico, String pass,
			boolean bloccato, boolean elimato, boolean cancellato,
			boolean attivato, Date dataRichiesta, Date dataAccettazione,
			int punteggioFeedback, Set<Itinerario> itinerarios,
			Set<Questionario> questionarios,
			Set<Feedback> feedbacksForSegnalatore,
			Set<Cybercontadino> cybercontadinos,
			Set<Feedback> feedbacksForValidatore,
			Set<Feedback> feedbacksForSegnalatore_1, Set<Ordine> ordines,
			Set<Itinerario> itinerarios_1, Set<Ruolo> ruolos,
			Set<Cybercontadino> cybercontadinos_1, Set<Ruolo> ruolos_1,
			Set<Feedback> feedbacksForDestinatario,
			Set<Feedback> feedbacksForDestinatario_1,
			Set<Feedback> feedbacksForValidatore_1, Set<Ordine> ordines_1,
			Set<Questionario> questionarios_1) {
		this.username = username;
		this.utente = utente;
		this.pagamentoelettronico = pagamentoelettronico;
		this.pass = pass;
		this.bloccato = bloccato;
		this.elimato = elimato;
		this.cancellato = cancellato;
		this.attivato = attivato;
		this.dataRichiesta = dataRichiesta;
		this.dataAccettazione = dataAccettazione;
		this.punteggioFeedback = punteggioFeedback;
		this.itinerarios = itinerarios;
		this.questionarios = questionarios;
		this.feedbacksForSegnalatore = feedbacksForSegnalatore;
		this.cybercontadinos = cybercontadinos;
		this.feedbacksForValidatore = feedbacksForValidatore;
		this.feedbacksForSegnalatore_1 = feedbacksForSegnalatore_1;
		this.ordines = ordines;
		this.itinerarios_1 = itinerarios_1;
		this.ruolos = ruolos;
		this.cybercontadinos_1 = cybercontadinos_1;
		this.ruolos_1 = ruolos_1;
		this.feedbacksForDestinatario = feedbacksForDestinatario;
		this.feedbacksForDestinatario_1 = feedbacksForDestinatario_1;
		this.feedbacksForValidatore_1 = feedbacksForValidatore_1;
		this.ordines_1 = ordines_1;
		this.questionarios_1 = questionarios_1;
	}

	@Id
	@Column(name = "Username", unique = true, nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Utente_CodiceFiscale", nullable = false)
	@NotNull
	public Utente getUtente() {
		return this.utente;
	}

	public void setUtente(Utente utente) {
		this.utente = utente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PagamentoElettronico_idPagamentoElettronico")
	public Pagamentoelettronico getPagamentoelettronico() {
		return this.pagamentoelettronico;
	}

	public void setPagamentoelettronico(
			Pagamentoelettronico pagamentoelettronico) {
		this.pagamentoelettronico = pagamentoelettronico;
	}

	@Column(name = "Pass", nullable = false, length = 32)
	@NotNull
	@Length(max = 32)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "Bloccato", nullable = false)
	@NotNull
	public boolean isBloccato() {
		return this.bloccato;
	}

	public void setBloccato(boolean bloccato) {
		this.bloccato = bloccato;
	}

	@Column(name = "Elimato", nullable = false)
	@NotNull
	public boolean isElimato() {
		return this.elimato;
	}

	public void setElimato(boolean elimato) {
		this.elimato = elimato;
	}

	@Column(name = "Cancellato", nullable = false)
	@NotNull
	public boolean isCancellato() {
		return this.cancellato;
	}

	public void setCancellato(boolean cancellato) {
		this.cancellato = cancellato;
	}

	@Column(name = "Attivato", nullable = false)
	@NotNull
	public boolean isAttivato() {
		return this.attivato;
	}

	public void setAttivato(boolean attivato) {
		this.attivato = attivato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DataRichiesta", nullable = false, length = 10)
	@NotNull
	public Date getDataRichiesta() {
		return this.dataRichiesta;
	}

	public void setDataRichiesta(Date dataRichiesta) {
		this.dataRichiesta = dataRichiesta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DataAccettazione", length = 10)
	public Date getDataAccettazione() {
		return this.dataAccettazione;
	}

	public void setDataAccettazione(Date dataAccettazione) {
		this.dataAccettazione = dataAccettazione;
	}

	@Column(name = "PunteggioFeedback", nullable = false)
	@NotNull
	public int getPunteggioFeedback() {
		return this.punteggioFeedback;
	}

	public void setPunteggioFeedback(int punteggioFeedback) {
		this.punteggioFeedback = punteggioFeedback;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Itinerario> getItinerarios() {
		return this.itinerarios;
	}

	public void setItinerarios(Set<Itinerario> itinerarios) {
		this.itinerarios = itinerarios;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Questionario> getQuestionarios() {
		return this.questionarios;
	}

	public void setQuestionarios(Set<Questionario> questionarios) {
		this.questionarios = questionarios;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "accountBySegnalatore")
	public Set<Feedback> getFeedbacksForSegnalatore() {
		return this.feedbacksForSegnalatore;
	}

	public void setFeedbacksForSegnalatore(Set<Feedback> feedbacksForSegnalatore) {
		this.feedbacksForSegnalatore = feedbacksForSegnalatore;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Cybercontadino> getCybercontadinos() {
		return this.cybercontadinos;
	}

	public void setCybercontadinos(Set<Cybercontadino> cybercontadinos) {
		this.cybercontadinos = cybercontadinos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "accountByValidatore")
	public Set<Feedback> getFeedbacksForValidatore() {
		return this.feedbacksForValidatore;
	}

	public void setFeedbacksForValidatore(Set<Feedback> feedbacksForValidatore) {
		this.feedbacksForValidatore = feedbacksForValidatore;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "accountBySegnalatore")
	public Set<Feedback> getFeedbacksForSegnalatore_1() {
		return this.feedbacksForSegnalatore_1;
	}

	public void setFeedbacksForSegnalatore_1(
			Set<Feedback> feedbacksForSegnalatore_1) {
		this.feedbacksForSegnalatore_1 = feedbacksForSegnalatore_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Ordine> getOrdines() {
		return this.ordines;
	}

	public void setOrdines(Set<Ordine> ordines) {
		this.ordines = ordines;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Itinerario> getItinerarios_1() {
		return this.itinerarios_1;
	}

	public void setItinerarios_1(Set<Itinerario> itinerarios_1) {
		this.itinerarios_1 = itinerarios_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Ruolo> getRuolos() {
		return this.ruolos;
	}

	public void setRuolos(Set<Ruolo> ruolos) {
		this.ruolos = ruolos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Cybercontadino> getCybercontadinos_1() {
		return this.cybercontadinos_1;
	}

	public void setCybercontadinos_1(Set<Cybercontadino> cybercontadinos_1) {
		this.cybercontadinos_1 = cybercontadinos_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Ruolo> getRuolos_1() {
		return this.ruolos_1;
	}

	public void setRuolos_1(Set<Ruolo> ruolos_1) {
		this.ruolos_1 = ruolos_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "accountByDestinatario")
	public Set<Feedback> getFeedbacksForDestinatario() {
		return this.feedbacksForDestinatario;
	}

	public void setFeedbacksForDestinatario(
			Set<Feedback> feedbacksForDestinatario) {
		this.feedbacksForDestinatario = feedbacksForDestinatario;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "accountByDestinatario")
	public Set<Feedback> getFeedbacksForDestinatario_1() {
		return this.feedbacksForDestinatario_1;
	}

	public void setFeedbacksForDestinatario_1(
			Set<Feedback> feedbacksForDestinatario_1) {
		this.feedbacksForDestinatario_1 = feedbacksForDestinatario_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "accountByValidatore")
	public Set<Feedback> getFeedbacksForValidatore_1() {
		return this.feedbacksForValidatore_1;
	}

	public void setFeedbacksForValidatore_1(
			Set<Feedback> feedbacksForValidatore_1) {
		this.feedbacksForValidatore_1 = feedbacksForValidatore_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Ordine> getOrdines_1() {
		return this.ordines_1;
	}

	public void setOrdines_1(Set<Ordine> ordines_1) {
		this.ordines_1 = ordines_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Questionario> getQuestionarios_1() {
		return this.questionarios_1;
	}

	public void setQuestionarios_1(Set<Questionario> questionarios_1) {
		this.questionarios_1 = questionarios_1;
	}

}
