package org.domain.SeamAmiciDelGas.entity;

// Generated 7-feb-2009 12.59.42 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Cybercontadino generated by hbm2java
 */
@Entity
@Table(name = "cybercontadino", catalog = "database_gas")
public class Cybercontadino implements java.io.Serializable {

	private int partitaIva;
	private Account account;
	private Comune comune;
	private String nomePresidente;
	private String indirizzo;
	private String cognomePresidente;
	private String nomeAzienda;
	private String pathAsl;
	private String urlWsdl;
	private String descrizioneAzienda;
	private int recapitoTelefonico;
	private String email;
	private String coordinate;
	private Integer comuneIdcomune;
	private Set<Questionario> questionarios = new HashSet<Questionario>(0);
	private Set<Questionario> questionarios_1 = new HashSet<Questionario>(0);
	private Set<Itinerario> itinerarios = new HashSet<Itinerario>(0);
	private Set<Itinerario> itinerarios_1 = new HashSet<Itinerario>(0);
	private Set<Articolo> articolos = new HashSet<Articolo>(0);
	private Set<Articolo> articolos_1 = new HashSet<Articolo>(0);
	private Set<Questionario> questionarios_2 = new HashSet<Questionario>(0);

	public Cybercontadino() {
	}

	public Cybercontadino(int partitaIva, Account account, Comune comune,
			String nomePresidente, String indirizzo, String cognomePresidente,
			String nomeAzienda, String pathAsl, int recapitoTelefonico,
			String email) {
		this.partitaIva = partitaIva;
		this.account = account;
		this.comune = comune;
		this.nomePresidente = nomePresidente;
		this.indirizzo = indirizzo;
		this.cognomePresidente = cognomePresidente;
		this.nomeAzienda = nomeAzienda;
		this.pathAsl = pathAsl;
		this.recapitoTelefonico = recapitoTelefonico;
		this.email = email;
	}

	public Cybercontadino(int partitaIva, Account account, Comune comune,
			String nomePresidente, String indirizzo, String cognomePresidente,
			String nomeAzienda, String pathAsl, String urlWsdl,
			String descrizioneAzienda, int recapitoTelefonico, String email,
			String coordinate, Integer comuneIdcomune,
			Set<Questionario> questionarios, Set<Questionario> questionarios_1,
			Set<Itinerario> itinerarios, Set<Itinerario> itinerarios_1,
			Set<Articolo> articolos, Set<Articolo> articolos_1,
			Set<Questionario> questionarios_2) {
		this.partitaIva = partitaIva;
		this.account = account;
		this.comune = comune;
		this.nomePresidente = nomePresidente;
		this.indirizzo = indirizzo;
		this.cognomePresidente = cognomePresidente;
		this.nomeAzienda = nomeAzienda;
		this.pathAsl = pathAsl;
		this.urlWsdl = urlWsdl;
		this.descrizioneAzienda = descrizioneAzienda;
		this.recapitoTelefonico = recapitoTelefonico;
		this.email = email;
		this.coordinate = coordinate;
		this.comuneIdcomune = comuneIdcomune;
		this.questionarios = questionarios;
		this.questionarios_1 = questionarios_1;
		this.itinerarios = itinerarios;
		this.itinerarios_1 = itinerarios_1;
		this.articolos = articolos;
		this.articolos_1 = articolos_1;
		this.questionarios_2 = questionarios_2;
	}

	@Id
	@Column(name = "PartitaIVA", unique = true, nullable = false)
	@NotNull
	public int getPartitaIva() {
		return this.partitaIva;
	}

	public void setPartitaIva(int partitaIva) {
		this.partitaIva = partitaIva;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Username", nullable = false)
	@NotNull
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Comune_ubicazione", nullable = false)
	@NotNull
	public Comune getComune() {
		return this.comune;
	}

	public void setComune(Comune comune) {
		this.comune = comune;
	}

	@Column(name = "NomePresidente", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNomePresidente() {
		return this.nomePresidente;
	}

	public void setNomePresidente(String nomePresidente) {
		this.nomePresidente = nomePresidente;
	}

	@Column(name = "Indirizzo", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	@Column(name = "CognomePresidente", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getCognomePresidente() {
		return this.cognomePresidente;
	}

	public void setCognomePresidente(String cognomePresidente) {
		this.cognomePresidente = cognomePresidente;
	}

	@Column(name = "NomeAzienda", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNomeAzienda() {
		return this.nomeAzienda;
	}

	public void setNomeAzienda(String nomeAzienda) {
		this.nomeAzienda = nomeAzienda;
	}

	@Column(name = "PathASL", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getPathAsl() {
		return this.pathAsl;
	}

	public void setPathAsl(String pathAsl) {
		this.pathAsl = pathAsl;
	}

	@Column(name = "UrlWSDL", length = 500)
	@Length(max = 500)
	public String getUrlWsdl() {
		return this.urlWsdl;
	}

	public void setUrlWsdl(String urlWsdl) {
		this.urlWsdl = urlWsdl;
	}

	@Column(name = "DescrizioneAzienda", length = 65535)
	@Length(max = 65535)
	public String getDescrizioneAzienda() {
		return this.descrizioneAzienda;
	}

	public void setDescrizioneAzienda(String descrizioneAzienda) {
		this.descrizioneAzienda = descrizioneAzienda;
	}

	@Column(name = "recapito_telefonico", nullable = false)
	@NotNull
	public int getRecapitoTelefonico() {
		return this.recapitoTelefonico;
	}

	public void setRecapitoTelefonico(int recapitoTelefonico) {
		this.recapitoTelefonico = recapitoTelefonico;
	}

	@Column(name = "email", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Coordinate", length = 500)
	@Length(max = 500)
	public String getCoordinate() {
		return this.coordinate;
	}

	public void setCoordinate(String coordinate) {
		this.coordinate = coordinate;
	}

	@Column(name = "Comune_IDComune")
	public Integer getComuneIdcomune() {
		return this.comuneIdcomune;
	}

	public void setComuneIdcomune(Integer comuneIdcomune) {
		this.comuneIdcomune = comuneIdcomune;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cybercontadino")
	public Set<Questionario> getQuestionarios() {
		return this.questionarios;
	}

	public void setQuestionarios(Set<Questionario> questionarios) {
		this.questionarios = questionarios;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cybercontadino")
	public Set<Questionario> getQuestionarios_1() {
		return this.questionarios_1;
	}

	public void setQuestionarios_1(Set<Questionario> questionarios_1) {
		this.questionarios_1 = questionarios_1;
	}

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cybercontadinos")
	public Set<Itinerario> getItinerarios() {
		return this.itinerarios;
	}

	public void setItinerarios(Set<Itinerario> itinerarios) {
		this.itinerarios = itinerarios;
	}

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cybercontadinos")
	public Set<Itinerario> getItinerarios_1() {
		return this.itinerarios_1;
	}

	public void setItinerarios_1(Set<Itinerario> itinerarios_1) {
		this.itinerarios_1 = itinerarios_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cybercontadino")
	public Set<Articolo> getArticolos() {
		return this.articolos;
	}

	public void setArticolos(Set<Articolo> articolos) {
		this.articolos = articolos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cybercontadino")
	public Set<Articolo> getArticolos_1() {
		return this.articolos_1;
	}

	public void setArticolos_1(Set<Articolo> articolos_1) {
		this.articolos_1 = articolos_1;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cybercontadino")
	public Set<Questionario> getQuestionarios_2() {
		return this.questionarios_2;
	}

	public void setQuestionarios_2(Set<Questionario> questionarios_2) {
		this.questionarios_2 = questionarios_2;
	}

}
