package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * CyberContadino generated by hbm2java
 */
@Entity
@Table(name = "CyberContadino", catalog = "database_gas")
public class CyberContadino implements java.io.Serializable {

	private int partitaIva;
	private String username;
	private String nomePresidente;
	private String indirizzo;
	private String cognomePresidente;
	private String nomeAzienda;
	private String pathAsl;
	private String urlWsdl;
	private String descrizioneAzienda;
	private Integer comuneIdcomune;
	private Integer recapitoTelefonico;
	private String email;
	private Set<Questionario> questionarios = new HashSet<Questionario>(0);

	public CyberContadino() {
	}

	public CyberContadino(int partitaIva, String username, String indirizzo,
			String nomeAzienda, String urlWsdl) {
		this.partitaIva = partitaIva;
		this.username = username;
		this.indirizzo = indirizzo;
		this.nomeAzienda = nomeAzienda;
		this.urlWsdl = urlWsdl;
	}

	public CyberContadino(int partitaIva, String username,
			String nomePresidente, String indirizzo, String cognomePresidente,
			String nomeAzienda, String pathAsl, String urlWsdl,
			String descrizioneAzienda, Integer comuneIdcomune,
			Integer recapitoTelefonico, String email,
			Set<Questionario> questionarios) {
		this.partitaIva = partitaIva;
		this.username = username;
		this.nomePresidente = nomePresidente;
		this.indirizzo = indirizzo;
		this.cognomePresidente = cognomePresidente;
		this.nomeAzienda = nomeAzienda;
		this.pathAsl = pathAsl;
		this.urlWsdl = urlWsdl;
		this.descrizioneAzienda = descrizioneAzienda;
		this.comuneIdcomune = comuneIdcomune;
		this.recapitoTelefonico = recapitoTelefonico;
		this.email = email;
		this.questionarios = questionarios;
	}

	@Id
	@Column(name = "PartitaIVA", unique = true, nullable = false)
	@NotNull
	public int getPartitaIva() {
		return this.partitaIva;
	}

	public void setPartitaIva(int partitaIva) {
		this.partitaIva = partitaIva;
	}

	@Column(name = "Username", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "NomePresidente", length = 50)
	@Length(max = 50)
	public String getNomePresidente() {
		return this.nomePresidente;
	}

	public void setNomePresidente(String nomePresidente) {
		this.nomePresidente = nomePresidente;
	}

	@Column(name = "Indirizzo", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	@Column(name = "CognomePresidente", length = 50)
	@Length(max = 50)
	public String getCognomePresidente() {
		return this.cognomePresidente;
	}

	public void setCognomePresidente(String cognomePresidente) {
		this.cognomePresidente = cognomePresidente;
	}

	@Column(name = "NomeAzienda", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNomeAzienda() {
		return this.nomeAzienda;
	}

	public void setNomeAzienda(String nomeAzienda) {
		this.nomeAzienda = nomeAzienda;
	}

	@Column(name = "PathASL", length = 500)
	@Length(max = 500)
	public String getPathAsl() {
		return this.pathAsl;
	}

	public void setPathAsl(String pathAsl) {
		this.pathAsl = pathAsl;
	}

	@Column(name = "UrlWSDL", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getUrlWsdl() {
		return this.urlWsdl;
	}

	public void setUrlWsdl(String urlWsdl) {
		this.urlWsdl = urlWsdl;
	}

	@Column(name = "DescrizioneAzienda", length = 65535)
	@Length(max = 65535)
	public String getDescrizioneAzienda() {
		return this.descrizioneAzienda;
	}

	public void setDescrizioneAzienda(String descrizioneAzienda) {
		this.descrizioneAzienda = descrizioneAzienda;
	}

	@Column(name = "Comune_IDComune")
	public Integer getComuneIdcomune() {
		return this.comuneIdcomune;
	}

	public void setComuneIdcomune(Integer comuneIdcomune) {
		this.comuneIdcomune = comuneIdcomune;
	}

	@Column(name = "recapito_telefonico")
	public Integer getRecapitoTelefonico() {
		return this.recapitoTelefonico;
	}

	public void setRecapitoTelefonico(Integer recapitoTelefonico) {
		this.recapitoTelefonico = recapitoTelefonico;
	}

	@Column(name = "email", length = 200)
	@Length(max = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cyberContadino")
	public Set<Questionario> getQuestionarios() {
		return this.questionarios;
	}

	public void setQuestionarios(Set<Questionario> questionarios) {
		this.questionarios = questionarios;
	}

}
