package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "Feedback", catalog = "database_gas")
public class Feedback implements java.io.Serializable {

	private Integer idfeedback;
	private int idordine;
	private String validatore;
	private String segnalatore;
	private String destinatario;
	private boolean analizzato;
	private String descrizione;
	private Date dataValidazione;
	private Date dataSegnalazione;
	private Integer punteggio;

	public Feedback() {
	}

	public Feedback(int idordine, String validatore, String segnalatore,
			String destinatario, boolean analizzato, Date dataValidazione,
			Date dataSegnalazione) {
		this.idordine = idordine;
		this.validatore = validatore;
		this.segnalatore = segnalatore;
		this.destinatario = destinatario;
		this.analizzato = analizzato;
		this.dataValidazione = dataValidazione;
		this.dataSegnalazione = dataSegnalazione;
	}

	public Feedback(int idordine, String validatore, String segnalatore,
			String destinatario, boolean analizzato, String descrizione,
			Date dataValidazione, Date dataSegnalazione, Integer punteggio) {
		this.idordine = idordine;
		this.validatore = validatore;
		this.segnalatore = segnalatore;
		this.destinatario = destinatario;
		this.analizzato = analizzato;
		this.descrizione = descrizione;
		this.dataValidazione = dataValidazione;
		this.dataSegnalazione = dataSegnalazione;
		this.punteggio = punteggio;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDFeedback", unique = true, nullable = false)
	public Integer getIdfeedback() {
		return this.idfeedback;
	}

	public void setIdfeedback(Integer idfeedback) {
		this.idfeedback = idfeedback;
	}

	@Column(name = "IDOrdine", nullable = false)
	@NotNull
	public int getIdordine() {
		return this.idordine;
	}

	public void setIdordine(int idordine) {
		this.idordine = idordine;
	}

	@Column(name = "Validatore", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getValidatore() {
		return this.validatore;
	}

	public void setValidatore(String validatore) {
		this.validatore = validatore;
	}

	@Column(name = "Segnalatore", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getSegnalatore() {
		return this.segnalatore;
	}

	public void setSegnalatore(String segnalatore) {
		this.segnalatore = segnalatore;
	}

	@Column(name = "Destinatario", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getDestinatario() {
		return this.destinatario;
	}

	public void setDestinatario(String destinatario) {
		this.destinatario = destinatario;
	}

	@Column(name = "Analizzato", nullable = false)
	@NotNull
	public boolean isAnalizzato() {
		return this.analizzato;
	}

	public void setAnalizzato(boolean analizzato) {
		this.analizzato = analizzato;
	}

	@Column(name = "Descrizione", length = 65535)
	@Length(max = 65535)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DataValidazione", nullable = false, length = 0)
	@NotNull
	public Date getDataValidazione() {
		return this.dataValidazione;
	}

	public void setDataValidazione(Date dataValidazione) {
		this.dataValidazione = dataValidazione;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DataSegnalazione", nullable = false, length = 0)
	@NotNull
	public Date getDataSegnalazione() {
		return this.dataSegnalazione;
	}

	public void setDataSegnalazione(Date dataSegnalazione) {
		this.dataSegnalazione = dataSegnalazione;
	}

	@Column(name = "Punteggio")
	public Integer getPunteggio() {
		return this.punteggio;
	}

	public void setPunteggio(Integer punteggio) {
		this.punteggio = punteggio;
	}

}
