package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.NotNull;

/**
 * ItinerarioHasCyberContadinoId generated by hbm2java
 */
@Embeddable
public class ItinerarioHasCyberContadinoId implements java.io.Serializable {

	private int iditinerario;
	private int partitaIva;

	public ItinerarioHasCyberContadinoId() {
	}

	public ItinerarioHasCyberContadinoId(int iditinerario, int partitaIva) {
		this.iditinerario = iditinerario;
		this.partitaIva = partitaIva;
	}

	@Column(name = "IDItinerario", nullable = false)
	@NotNull
	public int getIditinerario() {
		return this.iditinerario;
	}

	public void setIditinerario(int iditinerario) {
		this.iditinerario = iditinerario;
	}

	@Column(name = "PartitaIVA", nullable = false)
	@NotNull
	public int getPartitaIva() {
		return this.partitaIva;
	}

	public void setPartitaIva(int partitaIva) {
		this.partitaIva = partitaIva;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItinerarioHasCyberContadinoId))
			return false;
		ItinerarioHasCyberContadinoId castOther = (ItinerarioHasCyberContadinoId) other;

		return (this.getIditinerario() == castOther.getIditinerario())
				&& (this.getPartitaIva() == castOther.getPartitaIva());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIditinerario();
		result = 37 * result + this.getPartitaIva();
		return result;
	}

}
