package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.NotNull;

/**
 * ItinerarioHasOrdineId generated by hbm2java
 */
@Embeddable
public class ItinerarioHasOrdineId implements java.io.Serializable {

	private int idordine;
	private int iditinerario;

	public ItinerarioHasOrdineId() {
	}

	public ItinerarioHasOrdineId(int idordine, int iditinerario) {
		this.idordine = idordine;
		this.iditinerario = iditinerario;
	}

	@Column(name = "IDOrdine", nullable = false)
	@NotNull
	public int getIdordine() {
		return this.idordine;
	}

	public void setIdordine(int idordine) {
		this.idordine = idordine;
	}

	@Column(name = "IDItinerario", nullable = false)
	@NotNull
	public int getIditinerario() {
		return this.iditinerario;
	}

	public void setIditinerario(int iditinerario) {
		this.iditinerario = iditinerario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItinerarioHasOrdineId))
			return false;
		ItinerarioHasOrdineId castOther = (ItinerarioHasOrdineId) other;

		return (this.getIdordine() == castOther.getIdordine())
				&& (this.getIditinerario() == castOther.getIditinerario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdordine();
		result = 37 * result + this.getIditinerario();
		return result;
	}

}
