package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * PuntiDiConsegna generated by hbm2java
 */
@Entity
@Table(name = "Punti_di_Consegna", catalog = "database_gas")
public class PuntiDiConsegna implements java.io.Serializable {

	private Integer idpuntiConsegna;
	private int idcomune;
	private String indirizzo;
	private Integer coordinate;

	public PuntiDiConsegna() {
	}

	public PuntiDiConsegna(int idcomune, String indirizzo) {
		this.idcomune = idcomune;
		this.indirizzo = indirizzo;
	}

	public PuntiDiConsegna(int idcomune, String indirizzo, Integer coordinate) {
		this.idcomune = idcomune;
		this.indirizzo = indirizzo;
		this.coordinate = coordinate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDPuntiConsegna", unique = true, nullable = false)
	public Integer getIdpuntiConsegna() {
		return this.idpuntiConsegna;
	}

	public void setIdpuntiConsegna(Integer idpuntiConsegna) {
		this.idpuntiConsegna = idpuntiConsegna;
	}

	@Column(name = "IDComune", nullable = false)
	@NotNull
	public int getIdcomune() {
		return this.idcomune;
	}

	public void setIdcomune(int idcomune) {
		this.idcomune = idcomune;
	}

	@Column(name = "Indirizzo", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	@Column(name = "Coordinate")
	public Integer getCoordinate() {
		return this.coordinate;
	}

	public void setCoordinate(Integer coordinate) {
		this.coordinate = coordinate;
	}

}
