package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Questionario generated by hbm2java
 */
@Entity
@Table(name = "questionario", catalog = "database_gas")
public class Questionario implements java.io.Serializable {

	private Integer idquestionario;
	private Account account;
	private CyberContadino cyberContadino;
	private int votoProdotti;
	private int votoStabile;
	private int votoIgiene;
	private int votoAllevamento;
	private int votoProfessionalita;
	private int votoGlobale;
	private String commenti;
	private Boolean visionato;
	private Date dataVisita;
	private Date dataCompilazione;

	public Questionario() {
	}

	public Questionario(int votoProdotti, int votoStabile, int votoIgiene,
			int votoAllevamento, int votoProfessionalita, int votoGlobale) {
		this.votoProdotti = votoProdotti;
		this.votoStabile = votoStabile;
		this.votoIgiene = votoIgiene;
		this.votoAllevamento = votoAllevamento;
		this.votoProfessionalita = votoProfessionalita;
		this.votoGlobale = votoGlobale;
	}

	public Questionario(Account account, CyberContadino cyberContadino,
			int votoProdotti, int votoStabile, int votoIgiene,
			int votoAllevamento, int votoProfessionalita, int votoGlobale,
			String commenti, Boolean visionato, Date dataVisita,
			Date dataCompilazione) {
		this.account = account;
		this.cyberContadino = cyberContadino;
		this.votoProdotti = votoProdotti;
		this.votoStabile = votoStabile;
		this.votoIgiene = votoIgiene;
		this.votoAllevamento = votoAllevamento;
		this.votoProfessionalita = votoProfessionalita;
		this.votoGlobale = votoGlobale;
		this.commenti = commenti;
		this.visionato = visionato;
		this.dataVisita = dataVisita;
		this.dataCompilazione = dataCompilazione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idquestionario", unique = true, nullable = false)
	public Integer getIdquestionario() {
		return this.idquestionario;
	}

	public void setIdquestionario(Integer idquestionario) {
		this.idquestionario = idquestionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Account_Username")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CyberContadino_PartitaIVA")
	public CyberContadino getCyberContadino() {
		return this.cyberContadino;
	}

	public void setCyberContadino(CyberContadino cyberContadino) {
		this.cyberContadino = cyberContadino;
	}

	@Column(name = "voto_prodotti", nullable = false)
	@NotNull
	public int getVotoProdotti() {
		return this.votoProdotti;
	}

	public void setVotoProdotti(int votoProdotti) {
		this.votoProdotti = votoProdotti;
	}

	@Column(name = "voto_stabile", nullable = false)
	@NotNull
	public int getVotoStabile() {
		return this.votoStabile;
	}

	public void setVotoStabile(int votoStabile) {
		this.votoStabile = votoStabile;
	}

	@Column(name = "voto_igiene", nullable = false)
	@NotNull
	public int getVotoIgiene() {
		return this.votoIgiene;
	}

	public void setVotoIgiene(int votoIgiene) {
		this.votoIgiene = votoIgiene;
	}

	@Column(name = "voto_allevamento", nullable = false)
	@NotNull
	public int getVotoAllevamento() {
		return this.votoAllevamento;
	}

	public void setVotoAllevamento(int votoAllevamento) {
		this.votoAllevamento = votoAllevamento;
	}

	@Column(name = "voto_professionalita", nullable = false)
	@NotNull
	public int getVotoProfessionalita() {
		return this.votoProfessionalita;
	}

	public void setVotoProfessionalita(int votoProfessionalita) {
		this.votoProfessionalita = votoProfessionalita;
	}

	@Column(name = "voto_globale", nullable = false)
	@NotNull
	public int getVotoGlobale() {
		return this.votoGlobale;
	}

	public void setVotoGlobale(int votoGlobale) {
		this.votoGlobale = votoGlobale;
	}

	@Column(name = "commenti", length = 500)
	@Length(max = 500)
	public String getCommenti() {
		return this.commenti;
	}

	public void setCommenti(String commenti) {
		this.commenti = commenti;
	}

	@Column(name = "visionato")
	public Boolean getVisionato() {
		return this.visionato;
	}

	public void setVisionato(Boolean visionato) {
		this.visionato = visionato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_visita", length = 0)
	public Date getDataVisita() {
		return this.dataVisita;
	}

	public void setDataVisita(Date dataVisita) {
		this.dataVisita = dataVisita;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_compilazione", length = 0)
	public Date getDataCompilazione() {
		return this.dataCompilazione;
	}

	public void setDataCompilazione(Date dataCompilazione) {
		this.dataCompilazione = dataCompilazione;
	}

}
