package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Ruolo generated by hbm2java
 */
@Entity
@Table(name = "Ruolo", catalog = "database_gas")
public class Ruolo implements java.io.Serializable {

	private Integer idruolo;
	private String username;
	private String tipo;

	public Ruolo() {
	}

	public Ruolo(String username, String tipo) {
		this.username = username;
		this.tipo = tipo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDRuolo", unique = true, nullable = false)
	public Integer getIdruolo() {
		return this.idruolo;
	}

	public void setIdruolo(Integer idruolo) {
		this.idruolo = idruolo;
	}

	@Column(name = "Username", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Tipo", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
