package org.domain.SeamAmiciDelGas.entity;

// Generated 7-feb-2009 12.59.42 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Ruolo generated by hbm2java
 */
@Entity
@Table(name = "ruolo", catalog = "database_gas")
public class Ruolo implements java.io.Serializable {

	private Integer idruolo;
	private Account account;
	private String tipo;

	public Ruolo() {
	}

	public Ruolo(Account account, String tipo) {
		this.account = account;
		this.tipo = tipo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDRuolo", unique = true, nullable = false)
	public Integer getIdruolo() {
		return this.idruolo;
	}

	public void setIdruolo(Integer idruolo) {
		this.idruolo = idruolo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Username", nullable = false)
	@NotNull
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "Tipo", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
