package org.domain.SeamAmiciDelGas.entity;

// Generated 7-feb-2009 13.24.15 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.domain.SeamAmiciDelGas.validator.DataAnnotation;
import org.hibernate.validator.Email;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
import org.hibernate.validator.Pattern;
import org.jboss.seam.ScopeType;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Scope;
import org.jboss.seam.annotations.Role;

/**
 * Utente generated by hbm2java
 */
@Entity
@Table(name = "utente", catalog = "database_gas")
@Role(name = "currentUser", scope = ScopeType.SESSION)
@Name(value="newUtente")
@Scope(value=ScopeType.SESSION)
public class Utente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8844807917627730444L;
	private String codiceFiscale;
	private Comune comuneByComuneNascita;
	private Comune comuneByIdcomune;
	private String nome;
	private String cognome;
	private Date dataNascita;
	private char sesso;
	private String pathQuestionario;
	private String indirizzo;
	private String recapitoTelefonico;
	@Email (message="errore")
	private String email;
	private Set<Patente> patentes = new HashSet<Patente>(0);
	private Set<Account> accounts = new HashSet<Account>(0);

	public Utente() {
	}

	public Utente(String codiceFiscale, Comune comuneByComuneNascita,
			Comune comuneByIdcomune, String nome, String cognome,
			Date dataNascita, char sesso, String indirizzo,
			String recapitoTelefonico, String email) {
		this.codiceFiscale = codiceFiscale;
		this.comuneByComuneNascita = comuneByComuneNascita;
		this.comuneByIdcomune = comuneByIdcomune;
		this.nome = nome;
		this.cognome = cognome;
		this.dataNascita = dataNascita;
		this.sesso = sesso;
		this.indirizzo = indirizzo;
		this.recapitoTelefonico = recapitoTelefonico;
		this.email = email;
	}

	public Utente(String codiceFiscale, Comune comuneByComuneNascita,
			Comune comuneByIdcomune, String nome, String cognome,
			Date dataNascita, char sesso, String pathQuestionario,
			String indirizzo, String recapitoTelefonico, String email,
			Set<Patente> patentes, Set<Account> accounts) {
		this.codiceFiscale = codiceFiscale;
		this.comuneByComuneNascita = comuneByComuneNascita;
		this.comuneByIdcomune = comuneByIdcomune;
		this.nome = nome;
		this.cognome = cognome;
		this.dataNascita = dataNascita;
		this.sesso = sesso;
		this.pathQuestionario = pathQuestionario;
		this.indirizzo = indirizzo;
		this.recapitoTelefonico = recapitoTelefonico;
		this.email = email;
		this.patentes = patentes;
		this.accounts = accounts;
	}

	@Id
	@Column(name = "CodiceFiscale", unique = true, nullable = false, length = 16)
	@NotNull
	@Length(max = 16)
	@Pattern(regex="^[a-zA-z]{6}[0-9]{2}[a-zA-z][0-9]{2}[a-zA-Z][0-9]{3}[a-zA-Z]$", message="formato codice fiscale non corretto") 
	public String getCodiceFiscale() {
		return this.codiceFiscale;
	}

	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Comune_nascita", nullable = false)
	@NotNull
	public Comune getComuneByComuneNascita() {
		return this.comuneByComuneNascita;
	}

	public void setComuneByComuneNascita(Comune comuneByComuneNascita) {
		this.comuneByComuneNascita = comuneByComuneNascita;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDComune", nullable = false)
	@NotNull
	public Comune getComuneByIdcomune() {
		return this.comuneByIdcomune;
	}

	public void setComuneByIdcomune(Comune comuneByIdcomune) {
		this.comuneByIdcomune = comuneByIdcomune;
	}

	@Column(name = "Nome", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "Cognome", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DataNascita", nullable = false, length = 10)
	@NotNull
	@DataAnnotation
	public Date getDataNascita() {
		return this.dataNascita;
	}

	public void setDataNascita(Date dataNascita) {
		this.dataNascita = dataNascita;
	}

	@Column(name = "Sesso", nullable = false)
	@NotNull
	public char getSesso() {
		return this.sesso;
	}

	public void setSesso(char sesso) {
		this.sesso = sesso;
	}

	@Column(name = "PathQuestionario", length = 500)
	@Length(max = 500)
	public String getPathQuestionario() {
		return this.pathQuestionario;
	}

	public void setPathQuestionario(String pathQuestionario) {
		this.pathQuestionario = pathQuestionario;
	}

	@Column(name = "Indirizzo", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	@Column(name = "RecapitoTelefonico", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getRecapitoTelefonico() {
		return this.recapitoTelefonico;
	}

	public void setRecapitoTelefonico(String recapitoTelefonico) {
		this.recapitoTelefonico = recapitoTelefonico;
	}

	@Column(name = "email", nullable = false, length = 70)
	@NotNull
	@Length(max = 70)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "utente")
	public Set<Patente> getPatentes() {
		return this.patentes;
	}

	public void setPatentes(Set<Patente> patentes) {
		this.patentes = patentes;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "utente")
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
