package org.domain.seamgas.entity;

// Generated 1-feb-2009 18.05.54 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Articolo generated by hbm2java
 */
@Entity
@Table(name = "articolo", catalog = "seam")
public class Articolo implements java.io.Serializable {

	private Integer idarticolo;
	private String codiceEsterno;
	private String descrizione;
	private Boolean prenotazioneLungoTermine;
	private Set<Ordine> ordines = new HashSet<Ordine>(0);
	private Set<Cybercontadino> cybercontadinos = new HashSet<Cybercontadino>(0);

	public Articolo() {
	}

	public Articolo(String codiceEsterno) {
		this.codiceEsterno = codiceEsterno;
	}

	public Articolo(String codiceEsterno, String descrizione,
			Boolean prenotazioneLungoTermine, Set<Ordine> ordines,
			Set<Cybercontadino> cybercontadinos) {
		this.codiceEsterno = codiceEsterno;
		this.descrizione = descrizione;
		this.prenotazioneLungoTermine = prenotazioneLungoTermine;
		this.ordines = ordines;
		this.cybercontadinos = cybercontadinos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDArticolo", unique = true, nullable = false)
	public Integer getIdarticolo() {
		return this.idarticolo;
	}

	public void setIdarticolo(Integer idarticolo) {
		this.idarticolo = idarticolo;
	}

	@Column(name = "CodiceEsterno", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getCodiceEsterno() {
		return this.codiceEsterno;
	}

	public void setCodiceEsterno(String codiceEsterno) {
		this.codiceEsterno = codiceEsterno;
	}

	@Column(name = "Descrizione", length = 65535)
	@Length(max = 65535)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "PrenotazioneLungoTermine")
	public Boolean getPrenotazioneLungoTermine() {
		return this.prenotazioneLungoTermine;
	}

	public void setPrenotazioneLungoTermine(Boolean prenotazioneLungoTermine) {
		this.prenotazioneLungoTermine = prenotazioneLungoTermine;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "articolo")
	public Set<Ordine> getOrdines() {
		return this.ordines;
	}

	public void setOrdines(Set<Ordine> ordines) {
		this.ordines = ordines;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "articolo")
	public Set<Cybercontadino> getCybercontadinos() {
		return this.cybercontadinos;
	}

	public void setCybercontadinos(Set<Cybercontadino> cybercontadinos) {
		this.cybercontadinos = cybercontadinos;
	}

}
