package org.domain.seamgas.entity;

// Generated 1-feb-2009 18.05.54 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Comune generated by hbm2java
 */
@Entity
@Table(name = "comune", catalog = "seam")
public class Comune implements java.io.Serializable {

	private Integer idcomune;
	private String nomeComune;
	private String provincia;
	private int cap;
	private Set<Utente> utentes = new HashSet<Utente>(0);
	private Set<Cybercontadino> cybercontadinos = new HashSet<Cybercontadino>(0);
	private Set<PuntiDiConsegna> puntiDiConsegnas = new HashSet<PuntiDiConsegna>(
			0);

	public Comune() {
	}

	public Comune(String nomeComune, String provincia, int cap) {
		this.nomeComune = nomeComune;
		this.provincia = provincia;
		this.cap = cap;
	}

	public Comune(String nomeComune, String provincia, int cap,
			Set<Utente> utentes, Set<Cybercontadino> cybercontadinos,
			Set<PuntiDiConsegna> puntiDiConsegnas) {
		this.nomeComune = nomeComune;
		this.provincia = provincia;
		this.cap = cap;
		this.utentes = utentes;
		this.cybercontadinos = cybercontadinos;
		this.puntiDiConsegnas = puntiDiConsegnas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDComune", unique = true, nullable = false)
	public Integer getIdcomune() {
		return this.idcomune;
	}

	public void setIdcomune(Integer idcomune) {
		this.idcomune = idcomune;
	}

	@Column(name = "NomeComune", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNomeComune() {
		return this.nomeComune;
	}

	public void setNomeComune(String nomeComune) {
		this.nomeComune = nomeComune;
	}

	@Column(name = "Provincia", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "CAP", nullable = false)
	@NotNull
	public int getCap() {
		return this.cap;
	}

	public void setCap(int cap) {
		this.cap = cap;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "comune")
	public Set<Utente> getUtentes() {
		return this.utentes;
	}

	public void setUtentes(Set<Utente> utentes) {
		this.utentes = utentes;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "comune")
	public Set<Cybercontadino> getCybercontadinos() {
		return this.cybercontadinos;
	}

	public void setCybercontadinos(Set<Cybercontadino> cybercontadinos) {
		this.cybercontadinos = cybercontadinos;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "comune")
	public Set<PuntiDiConsegna> getPuntiDiConsegnas() {
		return this.puntiDiConsegnas;
	}

	public void setPuntiDiConsegnas(Set<PuntiDiConsegna> puntiDiConsegnas) {
		this.puntiDiConsegnas = puntiDiConsegnas;
	}

}
