package org.domain.seamgas.entity;

// Generated 1-feb-2009 18.05.54 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Cybercontadino generated by hbm2java
 */
@Entity
@Table(name = "cybercontadino", catalog = "seam")
public class Cybercontadino implements java.io.Serializable {

	private int partitaIva;
	private Account account;
	private Comune comune;
	private Articolo articolo;
	private String nomePresidente;
	private String indirizzo;
	private String cognomePresidente;
	private String nomeAzienda;
	private String pathQuestionario;
	private String urlWisdl;
	private String descrizioneAzienda;
	private Set<Itinerario> itinerarios = new HashSet<Itinerario>(0);

	public Cybercontadino() {
	}

	public Cybercontadino(int partitaIva, Account account, Comune comune,
			Articolo articolo, String indirizzo, String nomeAzienda,
			String urlWisdl) {
		this.partitaIva = partitaIva;
		this.account = account;
		this.comune = comune;
		this.articolo = articolo;
		this.indirizzo = indirizzo;
		this.nomeAzienda = nomeAzienda;
		this.urlWisdl = urlWisdl;
	}

	public Cybercontadino(int partitaIva, Account account, Comune comune,
			Articolo articolo, String nomePresidente, String indirizzo,
			String cognomePresidente, String nomeAzienda,
			String pathQuestionario, String urlWisdl,
			String descrizioneAzienda, Set<Itinerario> itinerarios) {
		this.partitaIva = partitaIva;
		this.account = account;
		this.comune = comune;
		this.articolo = articolo;
		this.nomePresidente = nomePresidente;
		this.indirizzo = indirizzo;
		this.cognomePresidente = cognomePresidente;
		this.nomeAzienda = nomeAzienda;
		this.pathQuestionario = pathQuestionario;
		this.urlWisdl = urlWisdl;
		this.descrizioneAzienda = descrizioneAzienda;
		this.itinerarios = itinerarios;
	}

	@Id
	@Column(name = "PartitaIVA", unique = true, nullable = false)
	@NotNull
	public int getPartitaIva() {
		return this.partitaIva;
	}

	public void setPartitaIva(int partitaIva) {
		this.partitaIva = partitaIva;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Username", nullable = false)
	@NotNull
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Comune_IDComune", nullable = false)
	@NotNull
	public Comune getComune() {
		return this.comune;
	}

	public void setComune(Comune comune) {
		this.comune = comune;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDArticolo", nullable = false)
	@NotNull
	public Articolo getArticolo() {
		return this.articolo;
	}

	public void setArticolo(Articolo articolo) {
		this.articolo = articolo;
	}

	@Column(name = "NomePresidente", length = 50)
	@Length(max = 50)
	public String getNomePresidente() {
		return this.nomePresidente;
	}

	public void setNomePresidente(String nomePresidente) {
		this.nomePresidente = nomePresidente;
	}

	@Column(name = "Indirizzo", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	@Column(name = "CognomePresidente", length = 50)
	@Length(max = 50)
	public String getCognomePresidente() {
		return this.cognomePresidente;
	}

	public void setCognomePresidente(String cognomePresidente) {
		this.cognomePresidente = cognomePresidente;
	}

	@Column(name = "NomeAzienda", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNomeAzienda() {
		return this.nomeAzienda;
	}

	public void setNomeAzienda(String nomeAzienda) {
		this.nomeAzienda = nomeAzienda;
	}

	@Column(name = "PathQuestionario", length = 500)
	@Length(max = 500)
	public String getPathQuestionario() {
		return this.pathQuestionario;
	}

	public void setPathQuestionario(String pathQuestionario) {
		this.pathQuestionario = pathQuestionario;
	}

	@Column(name = "UrlWISDL", nullable = false, length = 500)
	@NotNull
	@Length(max = 500)
	public String getUrlWisdl() {
		return this.urlWisdl;
	}

	public void setUrlWisdl(String urlWisdl) {
		this.urlWisdl = urlWisdl;
	}

	@Column(name = "DescrizioneAzienda", length = 65535)
	@Length(max = 65535)
	public String getDescrizioneAzienda() {
		return this.descrizioneAzienda;
	}

	public void setDescrizioneAzienda(String descrizioneAzienda) {
		this.descrizioneAzienda = descrizioneAzienda;
	}

	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cybercontadinos")
	public Set<Itinerario> getItinerarios() {
		return this.itinerarios;
	}

	public void setItinerarios(Set<Itinerario> itinerarios) {
		this.itinerarios = itinerarios;
	}

}
