package org.domain.seamgas.entity;

// Generated 1-feb-2009 18.05.54 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.hibernate.validator.NotNull;

/**
 * ItinerarioHasPuntiDiConsegnaId generated by hbm2java
 */
@Embeddable
public class ItinerarioHasPuntiDiConsegnaId implements java.io.Serializable {

	private int idpuntiConsegna;
	private int iditinerario;

	public ItinerarioHasPuntiDiConsegnaId() {
	}

	public ItinerarioHasPuntiDiConsegnaId(int idpuntiConsegna, int iditinerario) {
		this.idpuntiConsegna = idpuntiConsegna;
		this.iditinerario = iditinerario;
	}

	@Column(name = "IDPuntiConsegna", nullable = false)
	@NotNull
	public int getIdpuntiConsegna() {
		return this.idpuntiConsegna;
	}

	public void setIdpuntiConsegna(int idpuntiConsegna) {
		this.idpuntiConsegna = idpuntiConsegna;
	}

	@Column(name = "IDItinerario", nullable = false)
	@NotNull
	public int getIditinerario() {
		return this.iditinerario;
	}

	public void setIditinerario(int iditinerario) {
		this.iditinerario = iditinerario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItinerarioHasPuntiDiConsegnaId))
			return false;
		ItinerarioHasPuntiDiConsegnaId castOther = (ItinerarioHasPuntiDiConsegnaId) other;

		return (this.getIdpuntiConsegna() == castOther.getIdpuntiConsegna())
				&& (this.getIditinerario() == castOther.getIditinerario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpuntiConsegna();
		result = 37 * result + this.getIditinerario();
		return result;
	}

}
