package org.domain.seamgas.entity;

// Generated 1-feb-2009 18.05.54 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ItinerarioHasPuntiDiConsegna generated by hbm2java
 */
@Entity
@Table(name = "itinerario_has_punti di consegna", catalog = "seam")
public class ItinerarioHasPuntiDiConsegna implements java.io.Serializable {

	private ItinerarioHasPuntiDiConsegnaId id;

	public ItinerarioHasPuntiDiConsegna() {
	}

	public ItinerarioHasPuntiDiConsegna(ItinerarioHasPuntiDiConsegnaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idpuntiConsegna", column = @Column(name = "IDPuntiConsegna", nullable = false)),
			@AttributeOverride(name = "iditinerario", column = @Column(name = "IDItinerario", nullable = false)) })
	@NotNull
	public ItinerarioHasPuntiDiConsegnaId getId() {
		return this.id;
	}

	public void setId(ItinerarioHasPuntiDiConsegnaId id) {
		this.id = id;
	}

}
