package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Articolo generated by hbm2java
 */
@Entity
@Table(name = "Articolo", catalog = "database_gas")
public class Articolo implements java.io.Serializable {

	private Integer idarticolo;
	private String codiceEsterno;
	private String descrizione;
	private Boolean prenotazioneLungoTermine;
	private Integer cyberContadinoPartitaIva;

	public Articolo() {
	}

	public Articolo(String codiceEsterno) {
		this.codiceEsterno = codiceEsterno;
	}

	public Articolo(String codiceEsterno, String descrizione,
			Boolean prenotazioneLungoTermine, Integer cyberContadinoPartitaIva) {
		this.codiceEsterno = codiceEsterno;
		this.descrizione = descrizione;
		this.prenotazioneLungoTermine = prenotazioneLungoTermine;
		this.cyberContadinoPartitaIva = cyberContadinoPartitaIva;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDArticolo", unique = true, nullable = false)
	public Integer getIdarticolo() {
		return this.idarticolo;
	}

	public void setIdarticolo(Integer idarticolo) {
		this.idarticolo = idarticolo;
	}

	@Column(name = "CodiceEsterno", nullable = false, length = 45)
	@NotNull
	@Length(max = 45)
	public String getCodiceEsterno() {
		return this.codiceEsterno;
	}

	public void setCodiceEsterno(String codiceEsterno) {
		this.codiceEsterno = codiceEsterno;
	}

	@Column(name = "Descrizione", length = 65535)
	@Length(max = 65535)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	@Column(name = "PrenotazioneLungoTermine")
	public Boolean getPrenotazioneLungoTermine() {
		return this.prenotazioneLungoTermine;
	}

	public void setPrenotazioneLungoTermine(Boolean prenotazioneLungoTermine) {
		this.prenotazioneLungoTermine = prenotazioneLungoTermine;
	}

	@Column(name = "CyberContadino_PartitaIVA")
	public Integer getCyberContadinoPartitaIva() {
		return this.cyberContadinoPartitaIva;
	}

	public void setCyberContadinoPartitaIva(Integer cyberContadinoPartitaIva) {
		this.cyberContadinoPartitaIva = cyberContadinoPartitaIva;
	}

}
