package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Comune generated by hbm2java
 */
@Entity
@Table(name = "Comune", catalog = "database_gas")
public class Comune implements java.io.Serializable {

	private Integer idcomune;
	private String nomeComune;
	private String provincia;
	private int cap;

	public Comune() {
	}

	public Comune(String nomeComune, String provincia, int cap) {
		this.nomeComune = nomeComune;
		this.provincia = provincia;
		this.cap = cap;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDComune", unique = true, nullable = false)
	public Integer getIdcomune() {
		return this.idcomune;
	}

	public void setIdcomune(Integer idcomune) {
		this.idcomune = idcomune;
	}

	@Column(name = "NomeComune", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNomeComune() {
		return this.nomeComune;
	}

	public void setNomeComune(String nomeComune) {
		this.nomeComune = nomeComune;
	}

	@Column(name = "Provincia", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "CAP", nullable = false)
	@NotNull
	public int getCap() {
		return this.cap;
	}

	public void setCap(int cap) {
		this.cap = cap;
	}

}
