package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ItinerarioHasOrdine generated by hbm2java
 */
@Entity
@Table(name = "Itinerario_has_Ordine", catalog = "database_gas")
public class ItinerarioHasOrdine implements java.io.Serializable {

	private ItinerarioHasOrdineId id;

	public ItinerarioHasOrdine() {
	}

	public ItinerarioHasOrdine(ItinerarioHasOrdineId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idordine", column = @Column(name = "IDOrdine", nullable = false)),
			@AttributeOverride(name = "iditinerario", column = @Column(name = "IDItinerario", nullable = false)) })
	@NotNull
	public ItinerarioHasOrdineId getId() {
		return this.id;
	}

	public void setId(ItinerarioHasOrdineId id) {
		this.id = id;
	}

}
