package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Itinerario generated by hbm2java
 */
@Entity
@Table(name = "Itinerario", catalog = "database_gas")
public class Itinerario implements java.io.Serializable {

	private Integer iditinerario;
	private String username;
	private Date dataPartenza;
	private Date dataConsegna;
	private String documentazionePath;
	private Date dataCreazione;

	public Itinerario() {
	}

	public Itinerario(String username, Date dataPartenza, Date dataConsegna,
			Date dataCreazione) {
		this.username = username;
		this.dataPartenza = dataPartenza;
		this.dataConsegna = dataConsegna;
		this.dataCreazione = dataCreazione;
	}

	public Itinerario(String username, Date dataPartenza, Date dataConsegna,
			String documentazionePath, Date dataCreazione) {
		this.username = username;
		this.dataPartenza = dataPartenza;
		this.dataConsegna = dataConsegna;
		this.documentazionePath = documentazionePath;
		this.dataCreazione = dataCreazione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDItinerario", unique = true, nullable = false)
	public Integer getIditinerario() {
		return this.iditinerario;
	}

	public void setIditinerario(Integer iditinerario) {
		this.iditinerario = iditinerario;
	}

	@Column(name = "Username", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DataPartenza", nullable = false, length = 0)
	@NotNull
	public Date getDataPartenza() {
		return this.dataPartenza;
	}

	public void setDataPartenza(Date dataPartenza) {
		this.dataPartenza = dataPartenza;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DataConsegna", nullable = false, length = 0)
	@NotNull
	public Date getDataConsegna() {
		return this.dataConsegna;
	}

	public void setDataConsegna(Date dataConsegna) {
		this.dataConsegna = dataConsegna;
	}

	@Column(name = "DocumentazionePath", length = 500)
	@Length(max = 500)
	public String getDocumentazionePath() {
		return this.documentazionePath;
	}

	public void setDocumentazionePath(String documentazionePath) {
		this.documentazionePath = documentazionePath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DataCreazione", nullable = false, length = 0)
	@NotNull
	public Date getDataCreazione() {
		return this.dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

}
