package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ItinerarioHasCyberContadino generated by hbm2java
 */
@Entity
@Table(name = "Itinerario_has_CyberContadino", catalog = "database_gas")
public class ItinerarioHasCyberContadino implements java.io.Serializable {

	private ItinerarioHasCyberContadinoId id;

	public ItinerarioHasCyberContadino() {
	}

	public ItinerarioHasCyberContadino(ItinerarioHasCyberContadinoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "iditinerario", column = @Column(name = "IDItinerario", nullable = false)),
			@AttributeOverride(name = "partitaIva", column = @Column(name = "PartitaIVA", nullable = false)) })
	@NotNull
	public ItinerarioHasCyberContadinoId getId() {
		return this.id;
	}

	public void setId(ItinerarioHasCyberContadinoId id) {
		this.id = id;
	}

}
