package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Ordine generated by hbm2java
 */
@Entity
@Table(name = "Ordine", catalog = "database_gas")
public class Ordine implements java.io.Serializable {

	private Integer idordine;
	private String username;
	private int idarticolo;
	private Date dataRichiesta;
	private boolean pendente;
	private int quantita;
	private int quantitaMinUtente;
	private Date dataMassimaConsegna;
	private Boolean cancellato;
	private Date dataCancellazioneAccettazione;

	public Ordine() {
	}

	public Ordine(String username, int idarticolo, Date dataRichiesta,
			boolean pendente, int quantita, int quantitaMinUtente) {
		this.username = username;
		this.idarticolo = idarticolo;
		this.dataRichiesta = dataRichiesta;
		this.pendente = pendente;
		this.quantita = quantita;
		this.quantitaMinUtente = quantitaMinUtente;
	}

	public Ordine(String username, int idarticolo, Date dataRichiesta,
			boolean pendente, int quantita, int quantitaMinUtente,
			Date dataMassimaConsegna, Boolean cancellato,
			Date dataCancellazioneAccettazione) {
		this.username = username;
		this.idarticolo = idarticolo;
		this.dataRichiesta = dataRichiesta;
		this.pendente = pendente;
		this.quantita = quantita;
		this.quantitaMinUtente = quantitaMinUtente;
		this.dataMassimaConsegna = dataMassimaConsegna;
		this.cancellato = cancellato;
		this.dataCancellazioneAccettazione = dataCancellazioneAccettazione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDOrdine", unique = true, nullable = false)
	public Integer getIdordine() {
		return this.idordine;
	}

	public void setIdordine(Integer idordine) {
		this.idordine = idordine;
	}

	@Column(name = "Username", nullable = false, length = 20)
	@NotNull
	@Length(max = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "IDArticolo", nullable = false)
	@NotNull
	public int getIdarticolo() {
		return this.idarticolo;
	}

	public void setIdarticolo(int idarticolo) {
		this.idarticolo = idarticolo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DataRichiesta", nullable = false, length = 0)
	@NotNull
	public Date getDataRichiesta() {
		return this.dataRichiesta;
	}

	public void setDataRichiesta(Date dataRichiesta) {
		this.dataRichiesta = dataRichiesta;
	}

	@Column(name = "Pendente", nullable = false)
	@NotNull
	public boolean isPendente() {
		return this.pendente;
	}

	public void setPendente(boolean pendente) {
		this.pendente = pendente;
	}

	@Column(name = "Quantita", nullable = false)
	@NotNull
	public int getQuantita() {
		return this.quantita;
	}

	public void setQuantita(int quantita) {
		this.quantita = quantita;
	}

	@Column(name = "QuantitaMinUtente", nullable = false)
	@NotNull
	public int getQuantitaMinUtente() {
		return this.quantitaMinUtente;
	}

	public void setQuantitaMinUtente(int quantitaMinUtente) {
		this.quantitaMinUtente = quantitaMinUtente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DataMassimaConsegna", length = 0)
	public Date getDataMassimaConsegna() {
		return this.dataMassimaConsegna;
	}

	public void setDataMassimaConsegna(Date dataMassimaConsegna) {
		this.dataMassimaConsegna = dataMassimaConsegna;
	}

	@Column(name = "Cancellato")
	public Boolean getCancellato() {
		return this.cancellato;
	}

	public void setCancellato(Boolean cancellato) {
		this.cancellato = cancellato;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DataCancellazioneAccettazione", length = 0)
	public Date getDataCancellazioneAccettazione() {
		return this.dataCancellazioneAccettazione;
	}

	public void setDataCancellazioneAccettazione(
			Date dataCancellazioneAccettazione) {
		this.dataCancellazioneAccettazione = dataCancellazioneAccettazione;
	}

}
