package org.domain.SeamAmiciDelGas.entity;

// Generated 6-feb-2009 11.41.06 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Patente generated by hbm2java
 */
@Entity
@Table(name = "Patente", catalog = "database_gas")
public class Patente implements java.io.Serializable {

	private Integer idpatente;
	private String codiceFiscale;
	private String tipo;

	public Patente() {
	}

	public Patente(String codiceFiscale, String tipo) {
		this.codiceFiscale = codiceFiscale;
		this.tipo = tipo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDPatente", unique = true, nullable = false)
	public Integer getIdpatente() {
		return this.idpatente;
	}

	public void setIdpatente(Integer idpatente) {
		this.idpatente = idpatente;
	}

	@Column(name = "CodiceFiscale", nullable = false, length = 16)
	@NotNull
	@Length(max = 16)
	public String getCodiceFiscale() {
		return this.codiceFiscale;
	}

	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale;
	}

	@Column(name = "Tipo", nullable = false, length = 2)
	@NotNull
	@Length(max = 2)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
